version: "3"

services:
  app:
    build: ./app
    image: sevenc-frontend:latest
    container_name: sevenc-frontend
    env_file: configs/.env
    environment:
      - NODE_ENV=development
    ports:
      - 8087:8087

  backend:
    build: ./backend
    image: sevenc-backend:latest
    container_name: sevenc-backend
    env_file: configs/.env
    environment:
      - NODE_ENV=development
    ports:
      - 8088:8088
